/**
 * OUT-02 Phase 3 — topic_paths seed data (V1 cascade catalogue)
 *
 * 101 rows across 12 step-1 categories, generated from
 * `01-design/content-creation-architecture.md` Part 3.
 *
 * Each row carries:
 *   - `path`: dotted natural key (e.g. 'audience.segment.problems.item')
 *   - `parentPath`: parent's `path` (null for step-1 categories) — the seeder
 *     resolves to a UUID at insert time
 *   - `dataQuery` / `hasDataCheck`: declarative configs interpreted by the
 *     topic-engine query layer (Phase 2 of OUT-02)
 *   - `promptTemplate`: leaf-only, with ${...} placeholders from
 *     prompt-vocabulary.md Group A
 *
 * Idempotent: upserts on `path`. Re-runnable.
 */

import type { NewTopicPath } from '@/lib/db/schema/content/topic-paths'

export interface TopicPathSeed extends Omit<NewTopicPath, 'id' | 'parentId' | 'nextStepId' | 'createdAt' | 'updatedAt'> {
  /** Parent's path. Null for step-1 categories. The seeder resolves to UUID. */
  parentPath: string | null
}

export const out02TopicPathSeeds: TopicPathSeed[] = [
  {
    path: `audience`,
    parentPath: null,
    stepLevel: 1,
    category: `audience`,
    label: `An audience segment`,
    surfaceKind: `category`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "table", "table": "dna_audience_segments", "filter": "status='active'"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `offer`,
    parentPath: null,
    stepLevel: 1,
    category: `offer`,
    label: `An offer`,
    surfaceKind: `category`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "table", "table": "dna_offers", "filter": "status='active'"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 1,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset`,
    parentPath: null,
    stepLevel: 1,
    category: `knowledge_asset`,
    label: `A knowledge asset`,
    surfaceKind: `category`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "table", "table": "dna_knowledge_assets", "filter": "status='active'"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 2,
    status: `active`,
    notes: null,
  },
  {
    path: `platform`,
    parentPath: null,
    stepLevel: 1,
    category: `platform`,
    label: `A content platform`,
    surfaceKind: `category`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "table", "table": "dna_platforms", "filter": "is_active=true"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 3,
    status: `active`,
    notes: null,
  },
  {
    path: `value_proposition`,
    parentPath: null,
    stepLevel: 1,
    category: `value_proposition`,
    label: `Value proposition`,
    surfaceKind: `category`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "single", "table": "dna_value_proposition", "field": "core_statement"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 4,
    status: `active`,
    notes: null,
  },
  {
    path: `brand_meaning`,
    parentPath: null,
    stepLevel: 1,
    category: `brand_meaning`,
    label: `Brand meaning`,
    surfaceKind: `category`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "table", "table": "dna_brand_meaning"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 5,
    status: `active`,
    notes: null,
  },
  {
    path: `brand_proof`,
    parentPath: null,
    stepLevel: 1,
    category: `brand_proof`,
    label: `Brand proof`,
    surfaceKind: `category`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "static"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 6,
    status: `active`,
    notes: null,
  },
  {
    path: `source_material`,
    parentPath: null,
    stepLevel: 1,
    category: `source_material`,
    label: `Source material`,
    surfaceKind: `category`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "table", "table": "src_source_documents", "filter": "is_archived=false"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 7,
    status: `active`,
    notes: null,
  },
  {
    path: `own_research`,
    parentPath: null,
    stepLevel: 1,
    category: `own_research`,
    label: `Own research`,
    surfaceKind: `category`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "table", "table": "src_own_research", "filter": "is_archived=false"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 8,
    status: `active`,
    notes: null,
  },
  {
    path: `mission`,
    parentPath: null,
    stepLevel: 1,
    category: `mission`,
    label: `A research mission`,
    surfaceKind: `category`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "table", "table": "missions"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 9,
    status: `active`,
    notes: null,
  },
  {
    path: `idea`,
    parentPath: null,
    stepLevel: 1,
    category: `idea`,
    label: `An idea`,
    surfaceKind: `category`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "table", "table": "ideas", "filter": "status='captured'"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 10,
    status: `active`,
    notes: null,
  },
  {
    path: `free_text`,
    parentPath: null,
    stepLevel: 1,
    category: `free_text`,
    label: `Free-text`,
    surfaceKind: `category`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "static"},
    multiSelect: false,
    promptTemplate: `The topic is: \${user_text}.`,
    displayOrder: 11,
    status: `active`,
    notes: `Step-1 escape hatch. The category row IS the leaf — user types into a textarea, no further steps.`,
  },
  {
    path: `audience.segment`,
    parentPath: `audience`,
    stepLevel: 2,
    category: `audience`,
    label: `Which segment?`,
    surfaceKind: `entity`,
    dataQuery: {"kind": "table", "table": "dna_audience_segments", "filter": "status='active'"},
    hasDataCheck: null,
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `audience.segment.problems`,
    parentPath: `audience.segment`,
    stepLevel: 3,
    category: `audience`,
    label: `Problems`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "jsonb_array", "table": "dna_audience_segments", "field": "problems", "parent_param": "segment_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 0,
    status: `active`,
    notes: `aspect_label = "problems, worries or fears"`,
  },
  {
    path: `audience.segment.problems.item`,
    parentPath: `audience.segment.problems`,
    stepLevel: 4,
    category: `audience`,
    label: `Problems`,
    surfaceKind: `item`,
    dataQuery: {"kind": "jsonb_array", "table": "dna_audience_segments", "field": "problems", "parent_param": "segment_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about an audience segment — \${segment_name} — specifically the \${aspect_label} they hold. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `audience.segment.desires`,
    parentPath: `audience.segment`,
    stepLevel: 3,
    category: `audience`,
    label: `Desires`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "jsonb_array", "table": "dna_audience_segments", "field": "desires", "parent_param": "segment_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 1,
    status: `active`,
    notes: `aspect_label = "desires/needs"`,
  },
  {
    path: `audience.segment.desires.item`,
    parentPath: `audience.segment.desires`,
    stepLevel: 4,
    category: `audience`,
    label: `Desires`,
    surfaceKind: `item`,
    dataQuery: {"kind": "jsonb_array", "table": "dna_audience_segments", "field": "desires", "parent_param": "segment_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about an audience segment — \${segment_name} — specifically the \${aspect_label} they hold. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `audience.segment.objections`,
    parentPath: `audience.segment`,
    stepLevel: 3,
    category: `audience`,
    label: `Objections`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "jsonb_array", "table": "dna_audience_segments", "field": "objections", "parent_param": "segment_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 2,
    status: `active`,
    notes: `aspect_label = "objections"`,
  },
  {
    path: `audience.segment.objections.item`,
    parentPath: `audience.segment.objections`,
    stepLevel: 4,
    category: `audience`,
    label: `Objections`,
    surfaceKind: `item`,
    dataQuery: {"kind": "jsonb_array", "table": "dna_audience_segments", "field": "objections", "parent_param": "segment_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about an audience segment — \${segment_name} — specifically the \${aspect_label} they hold. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `audience.segment.beliefs`,
    parentPath: `audience.segment`,
    stepLevel: 3,
    category: `audience`,
    label: `Beliefs`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "jsonb_array", "table": "dna_audience_segments", "field": "shared_beliefs", "parent_param": "segment_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 3,
    status: `active`,
    notes: `aspect_label = "beliefs"`,
  },
  {
    path: `audience.segment.beliefs.item`,
    parentPath: `audience.segment.beliefs`,
    stepLevel: 4,
    category: `audience`,
    label: `Beliefs`,
    surfaceKind: `item`,
    dataQuery: {"kind": "jsonb_array", "table": "dna_audience_segments", "field": "shared_beliefs", "parent_param": "segment_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about an audience segment — \${segment_name} — specifically the \${aspect_label} they hold. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `offer.entity`,
    parentPath: `offer`,
    stepLevel: 2,
    category: `offer`,
    label: `Which offer?`,
    surfaceKind: `entity`,
    dataQuery: {"kind": "table", "table": "dna_offers", "filter": "status='active'"},
    hasDataCheck: null,
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `offer.entity.outcomes`,
    parentPath: `offer.entity`,
    stepLevel: 3,
    category: `offer`,
    label: `Outcomes`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='outcome'", "parent_param": "offer_id", "parent_field": "offer_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `offer.entity.outcomes.item`,
    parentPath: `offer.entity.outcomes`,
    stepLevel: 4,
    category: `offer`,
    label: `Outcomes`,
    surfaceKind: `item`,
    dataQuery: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='outcome'", "parent_param": "offer_id", "parent_field": "offer_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about an offer — \${offer_name} — specifically the \${aspect_label}. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `offer.entity.benefits`,
    parentPath: `offer.entity`,
    stepLevel: 3,
    category: `offer`,
    label: `Benefits`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='benefit'", "parent_param": "offer_id", "parent_field": "offer_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 1,
    status: `active`,
    notes: null,
  },
  {
    path: `offer.entity.benefits.item`,
    parentPath: `offer.entity.benefits`,
    stepLevel: 4,
    category: `offer`,
    label: `Benefits`,
    surfaceKind: `item`,
    dataQuery: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='benefit'", "parent_param": "offer_id", "parent_field": "offer_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about an offer — \${offer_name} — specifically the \${aspect_label}. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `offer.entity.features`,
    parentPath: `offer.entity`,
    stepLevel: 3,
    category: `offer`,
    label: `Features`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='feature'", "parent_param": "offer_id", "parent_field": "offer_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 2,
    status: `active`,
    notes: null,
  },
  {
    path: `offer.entity.features.item`,
    parentPath: `offer.entity.features`,
    stepLevel: 4,
    category: `offer`,
    label: `Features`,
    surfaceKind: `item`,
    dataQuery: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='feature'", "parent_param": "offer_id", "parent_field": "offer_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about an offer — \${offer_name} — specifically the \${aspect_label}. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `offer.entity.bonuses`,
    parentPath: `offer.entity`,
    stepLevel: 3,
    category: `offer`,
    label: `Bonuses`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='bonus'", "parent_param": "offer_id", "parent_field": "offer_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 3,
    status: `active`,
    notes: null,
  },
  {
    path: `offer.entity.bonuses.item`,
    parentPath: `offer.entity.bonuses`,
    stepLevel: 4,
    category: `offer`,
    label: `Bonuses`,
    surfaceKind: `item`,
    dataQuery: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='bonus'", "parent_param": "offer_id", "parent_field": "offer_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about an offer — \${offer_name} — specifically the \${aspect_label}. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `offer.entity.faqs`,
    parentPath: `offer.entity`,
    stepLevel: 3,
    category: `offer`,
    label: `FAQs`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='faq'", "parent_param": "offer_id", "parent_field": "offer_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 4,
    status: `active`,
    notes: null,
  },
  {
    path: `offer.entity.faqs.item`,
    parentPath: `offer.entity.faqs`,
    stepLevel: 4,
    category: `offer`,
    label: `FAQs`,
    surfaceKind: `item`,
    dataQuery: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='faq'", "parent_param": "offer_id", "parent_field": "offer_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about an offer — \${offer_name} — specifically the \${aspect_label}. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `offer.entity.usp`,
    parentPath: `offer.entity`,
    stepLevel: 3,
    category: `offer`,
    label: `USP`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_offers", "field": "usp", "parent_param": "offer_id"},
    hasDataCheck: {"kind": "single", "table": "dna_offers", "field": "usp", "parent_param": "offer_id"},
    multiSelect: false,
    promptTemplate: `This is about an offer — \${offer_name} — specifically its \${aspect_label}: \${value}.`,
    displayOrder: 5,
    status: `active`,
    notes: `single-value aspect: aspect row IS the leaf, no step 4`,
  },
  {
    path: `offer.entity.guarantee`,
    parentPath: `offer.entity`,
    stepLevel: 3,
    category: `offer`,
    label: `Guarantee`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_offers", "field": "guarantee", "parent_param": "offer_id"},
    hasDataCheck: {"kind": "single", "table": "dna_offers", "field": "guarantee", "parent_param": "offer_id"},
    multiSelect: false,
    promptTemplate: `This is about an offer — \${offer_name} — specifically its \${aspect_label}: \${value}.`,
    displayOrder: 6,
    status: `active`,
    notes: `single-value aspect: aspect row IS the leaf, no step 4`,
  },
  {
    path: `offer.entity.pricing`,
    parentPath: `offer.entity`,
    stepLevel: 3,
    category: `offer`,
    label: `Pricing`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_offers", "field": "pricing", "parent_param": "offer_id"},
    hasDataCheck: {"kind": "single", "table": "dna_offers", "field": "pricing", "parent_param": "offer_id"},
    multiSelect: false,
    promptTemplate: `This is about an offer — \${offer_name} — specifically its \${aspect_label}: \${value}.`,
    displayOrder: 7,
    status: `active`,
    notes: `single-value aspect: aspect row IS the leaf, no step 4`,
  },
  {
    path: `offer.entity.cta`,
    parentPath: `offer.entity`,
    stepLevel: 3,
    category: `offer`,
    label: `CTA`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_offers", "field": "cta", "parent_param": "offer_id"},
    hasDataCheck: {"kind": "single", "table": "dna_offers", "field": "cta", "parent_param": "offer_id"},
    multiSelect: false,
    promptTemplate: `This is about an offer — \${offer_name} — specifically its \${aspect_label}: \${value}.`,
    displayOrder: 8,
    status: `active`,
    notes: `single-value aspect: aspect row IS the leaf, no step 4`,
  },
  {
    path: `offer.entity.stats`,
    parentPath: `offer.entity`,
    stepLevel: 3,
    category: `offer`,
    label: `Stats about this offer`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "table", "table": "src_statistics", "filter": "offer_ids @> jsonb_build_array(:offer_id) AND is_archived=false"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 9,
    status: `active`,
    notes: null,
  },
  {
    path: `offer.entity.stats.item`,
    parentPath: `offer.entity.stats`,
    stepLevel: 4,
    category: `offer`,
    label: `Stats about this offer`,
    surfaceKind: `item`,
    dataQuery: {"kind": "table", "table": "src_statistics", "filter": "offer_ids @> jsonb_build_array(:offer_id) AND is_archived=false"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about an offer — \${offer_name} — specifically the \${aspect_label}. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `offer.entity.testimonials`,
    parentPath: `offer.entity`,
    stepLevel: 3,
    category: `offer`,
    label: `Testimonials about this offer`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "table", "table": "src_testimonials", "filter": "offer_ids @> jsonb_build_array(:offer_id) AND is_archived=false"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 10,
    status: `active`,
    notes: null,
  },
  {
    path: `offer.entity.testimonials.item`,
    parentPath: `offer.entity.testimonials`,
    stepLevel: 4,
    category: `offer`,
    label: `Testimonials about this offer`,
    surfaceKind: `item`,
    dataQuery: {"kind": "table", "table": "src_testimonials", "filter": "offer_ids @> jsonb_build_array(:offer_id) AND is_archived=false"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about an offer — \${offer_name} — specifically the \${aspect_label}. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity`,
    parentPath: `knowledge_asset`,
    stepLevel: 2,
    category: `knowledge_asset`,
    label: `Which asset?`,
    surfaceKind: `entity`,
    dataQuery: {"kind": "table", "table": "dna_knowledge_assets", "filter": "status='active'"},
    hasDataCheck: null,
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.overview`,
    parentPath: `knowledge_asset.entity`,
    stepLevel: 3,
    category: `knowledge_asset`,
    label: `Overview`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_knowledge_assets", "field": "summary", "parent_param": "knowledge_asset_id"},
    hasDataCheck: {"kind": "single", "table": "dna_knowledge_assets", "field": "summary", "parent_param": "knowledge_asset_id"},
    multiSelect: false,
    promptTemplate: `This is about a knowledge asset — \${asset_name} — specifically its \${aspect_label}: \${value}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.philosophy`,
    parentPath: `knowledge_asset.entity`,
    stepLevel: 3,
    category: `knowledge_asset`,
    label: `Philosophy`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_knowledge_assets", "field": "principles", "parent_param": "knowledge_asset_id"},
    hasDataCheck: {"kind": "single", "table": "dna_knowledge_assets", "field": "principles", "parent_param": "knowledge_asset_id"},
    multiSelect: false,
    promptTemplate: `This is about a knowledge asset — \${asset_name} — specifically its \${aspect_label}: \${value}.`,
    displayOrder: 1,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.goals`,
    parentPath: `knowledge_asset.entity`,
    stepLevel: 3,
    category: `knowledge_asset`,
    label: `Goals`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_knowledge_assets", "field": "objectives", "parent_param": "knowledge_asset_id"},
    hasDataCheck: {"kind": "single", "table": "dna_knowledge_assets", "field": "objectives", "parent_param": "knowledge_asset_id"},
    multiSelect: false,
    promptTemplate: `This is about a knowledge asset — \${asset_name} — specifically its \${aspect_label}: \${value}.`,
    displayOrder: 2,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.problems_solved`,
    parentPath: `knowledge_asset.entity`,
    stepLevel: 3,
    category: `knowledge_asset`,
    label: `Problems solved`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_knowledge_assets", "field": "problems_solved", "parent_param": "knowledge_asset_id"},
    hasDataCheck: {"kind": "single", "table": "dna_knowledge_assets", "field": "problems_solved", "parent_param": "knowledge_asset_id"},
    multiSelect: false,
    promptTemplate: `This is about a knowledge asset — \${asset_name} — specifically its \${aspect_label}: \${value}.`,
    displayOrder: 3,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.contexts`,
    parentPath: `knowledge_asset.entity`,
    stepLevel: 3,
    category: `knowledge_asset`,
    label: `Contexts`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_knowledge_assets", "field": "contexts", "parent_param": "knowledge_asset_id"},
    hasDataCheck: {"kind": "single", "table": "dna_knowledge_assets", "field": "contexts", "parent_param": "knowledge_asset_id"},
    multiSelect: false,
    promptTemplate: `This is about a knowledge asset — \${asset_name} — specifically its \${aspect_label}: \${value}.`,
    displayOrder: 4,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.process`,
    parentPath: `knowledge_asset.entity`,
    stepLevel: 3,
    category: `knowledge_asset`,
    label: `Process`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "jsonb_array", "table": "dna_knowledge_assets", "field": "flow", "parent_param": "knowledge_asset_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 5,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.process.item`,
    parentPath: `knowledge_asset.entity.process`,
    stepLevel: 4,
    category: `knowledge_asset`,
    label: `Process`,
    surfaceKind: `item`,
    dataQuery: {"kind": "jsonb_array", "table": "dna_knowledge_assets", "field": "flow", "parent_param": "knowledge_asset_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about a knowledge asset — \${asset_name} — specifically the \${aspect_label}. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.outcomes`,
    parentPath: `knowledge_asset.entity`,
    stepLevel: 3,
    category: `knowledge_asset`,
    label: `Outcomes`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='outcome'", "parent_param": "knowledge_asset_id", "parent_field": "knowledge_asset_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 6,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.outcomes.item`,
    parentPath: `knowledge_asset.entity.outcomes`,
    stepLevel: 4,
    category: `knowledge_asset`,
    label: `Outcomes`,
    surfaceKind: `item`,
    dataQuery: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='outcome'", "parent_param": "knowledge_asset_id", "parent_field": "knowledge_asset_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about a knowledge asset — \${asset_name} — specifically the \${aspect_label}. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.benefits`,
    parentPath: `knowledge_asset.entity`,
    stepLevel: 3,
    category: `knowledge_asset`,
    label: `Benefits`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='benefit'", "parent_param": "knowledge_asset_id", "parent_field": "knowledge_asset_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 7,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.benefits.item`,
    parentPath: `knowledge_asset.entity.benefits`,
    stepLevel: 4,
    category: `knowledge_asset`,
    label: `Benefits`,
    surfaceKind: `item`,
    dataQuery: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='benefit'", "parent_param": "knowledge_asset_id", "parent_field": "knowledge_asset_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about a knowledge asset — \${asset_name} — specifically the \${aspect_label}. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.advantages`,
    parentPath: `knowledge_asset.entity`,
    stepLevel: 3,
    category: `knowledge_asset`,
    label: `Advantages`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='advantage'", "parent_param": "knowledge_asset_id", "parent_field": "knowledge_asset_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 8,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.advantages.item`,
    parentPath: `knowledge_asset.entity.advantages`,
    stepLevel: 4,
    category: `knowledge_asset`,
    label: `Advantages`,
    surfaceKind: `item`,
    dataQuery: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='advantage'", "parent_param": "knowledge_asset_id", "parent_field": "knowledge_asset_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about a knowledge asset — \${asset_name} — specifically the \${aspect_label}. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.features`,
    parentPath: `knowledge_asset.entity`,
    stepLevel: 3,
    category: `knowledge_asset`,
    label: `Features`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='feature'", "parent_param": "knowledge_asset_id", "parent_field": "knowledge_asset_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 9,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.features.item`,
    parentPath: `knowledge_asset.entity.features`,
    stepLevel: 4,
    category: `knowledge_asset`,
    label: `Features`,
    surfaceKind: `item`,
    dataQuery: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='feature'", "parent_param": "knowledge_asset_id", "parent_field": "knowledge_asset_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about a knowledge asset — \${asset_name} — specifically the \${aspect_label}. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.faqs`,
    parentPath: `knowledge_asset.entity`,
    stepLevel: 3,
    category: `knowledge_asset`,
    label: `FAQs`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='faq'", "parent_param": "knowledge_asset_id", "parent_field": "knowledge_asset_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 10,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.faqs.item`,
    parentPath: `knowledge_asset.entity.faqs`,
    stepLevel: 4,
    category: `knowledge_asset`,
    label: `FAQs`,
    surfaceKind: `item`,
    dataQuery: {"kind": "joined", "table": "dna_entity_outcomes", "filter": "kind='faq'", "parent_param": "knowledge_asset_id", "parent_field": "knowledge_asset_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about a knowledge asset — \${asset_name} — specifically the \${aspect_label}. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.stats`,
    parentPath: `knowledge_asset.entity`,
    stepLevel: 3,
    category: `knowledge_asset`,
    label: `Stats about this asset`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "table", "table": "src_statistics", "filter": "methodology_ids @> jsonb_build_array(:knowledge_asset_id) AND is_archived=false"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 11,
    status: `active`,
    notes: null,
  },
  {
    path: `knowledge_asset.entity.stats.item`,
    parentPath: `knowledge_asset.entity.stats`,
    stepLevel: 4,
    category: `knowledge_asset`,
    label: `Stats about this asset`,
    surfaceKind: `item`,
    dataQuery: {"kind": "table", "table": "src_statistics", "filter": "methodology_ids @> jsonb_build_array(:knowledge_asset_id) AND is_archived=false"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about a knowledge asset — \${asset_name} — specifically the \${aspect_label}. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `platform.entity`,
    parentPath: `platform`,
    stepLevel: 2,
    category: `platform`,
    label: `Which platform?`,
    surfaceKind: `entity`,
    dataQuery: {"kind": "table", "table": "dna_platforms", "filter": "is_active=true"},
    hasDataCheck: null,
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `platform.entity.overview`,
    parentPath: `platform.entity`,
    stepLevel: 3,
    category: `platform`,
    label: `Overview`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_platforms", "field": "primary_objective", "parent_param": "platform_id"},
    hasDataCheck: {"kind": "single", "table": "dna_platforms", "field": "primary_objective", "parent_param": "platform_id"},
    multiSelect: false,
    promptTemplate: `This is about a content platform — \${platform_name} — specifically its \${aspect_label}: \${value}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `platform.entity.positioning`,
    parentPath: `platform.entity`,
    stepLevel: 3,
    category: `platform`,
    label: `Positioning`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_platforms", "field": "usp", "parent_param": "platform_id"},
    hasDataCheck: {"kind": "single", "table": "dna_platforms", "field": "usp", "parent_param": "platform_id"},
    multiSelect: false,
    promptTemplate: `This is about a content platform — \${platform_name} — specifically its \${aspect_label}: \${value}.`,
    displayOrder: 2,
    status: `active`,
    notes: null,
  },
  {
    path: `platform.entity.topics`,
    parentPath: `platform.entity`,
    stepLevel: 3,
    category: `platform`,
    label: `Topic / themes`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "jsonb_array", "table": "dna_platforms", "field": "subtopic_ideas", "parent_param": "platform_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 1,
    status: `active`,
    notes: null,
  },
  {
    path: `platform.entity.topics.item`,
    parentPath: `platform.entity.topics`,
    stepLevel: 4,
    category: `platform`,
    label: `Topic / themes`,
    surfaceKind: `item`,
    dataQuery: {"kind": "jsonb_array", "table": "dna_platforms", "field": "subtopic_ideas", "parent_param": "platform_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about a content platform — \${platform_name} — specifically \${aspect_label}. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `platform.entity.formats`,
    parentPath: `platform.entity`,
    stepLevel: 3,
    category: `platform`,
    label: `Content formats`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "jsonb_array", "table": "dna_platforms", "field": "content_formats", "parent_param": "platform_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 3,
    status: `active`,
    notes: null,
  },
  {
    path: `platform.entity.formats.item`,
    parentPath: `platform.entity.formats`,
    stepLevel: 4,
    category: `platform`,
    label: `Content formats`,
    surfaceKind: `item`,
    dataQuery: {"kind": "jsonb_array", "table": "dna_platforms", "field": "content_formats", "parent_param": "platform_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about a content platform — \${platform_name} — specifically \${aspect_label}. Most specifically: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `value_proposition.core_statement`,
    parentPath: `value_proposition`,
    stepLevel: 2,
    category: `value_proposition`,
    label: `Core statement`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_value_proposition", "field": "core_statement"},
    hasDataCheck: {"kind": "single", "table": "dna_value_proposition", "field": "core_statement"},
    multiSelect: false,
    promptTemplate: `This is about the value proposition — specifically \${aspect_label}: \${value}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `value_proposition.target_customer`,
    parentPath: `value_proposition`,
    stepLevel: 2,
    category: `value_proposition`,
    label: `Target customer`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_value_proposition", "field": "target_customer"},
    hasDataCheck: {"kind": "single", "table": "dna_value_proposition", "field": "target_customer"},
    multiSelect: false,
    promptTemplate: `This is about the value proposition — specifically \${aspect_label}: \${value}.`,
    displayOrder: 1,
    status: `active`,
    notes: null,
  },
  {
    path: `value_proposition.problem_solved`,
    parentPath: `value_proposition`,
    stepLevel: 2,
    category: `value_proposition`,
    label: `Problem solved`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_value_proposition", "field": "problem_solved"},
    hasDataCheck: {"kind": "single", "table": "dna_value_proposition", "field": "problem_solved"},
    multiSelect: false,
    promptTemplate: `This is about the value proposition — specifically \${aspect_label}: \${value}.`,
    displayOrder: 2,
    status: `active`,
    notes: null,
  },
  {
    path: `value_proposition.outcome_delivered`,
    parentPath: `value_proposition`,
    stepLevel: 2,
    category: `value_proposition`,
    label: `Outcome delivered`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_value_proposition", "field": "outcome_delivered"},
    hasDataCheck: {"kind": "single", "table": "dna_value_proposition", "field": "outcome_delivered"},
    multiSelect: false,
    promptTemplate: `This is about the value proposition — specifically \${aspect_label}: \${value}.`,
    displayOrder: 3,
    status: `active`,
    notes: null,
  },
  {
    path: `value_proposition.unique_mechanism`,
    parentPath: `value_proposition`,
    stepLevel: 2,
    category: `value_proposition`,
    label: `Unique mechanism`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_value_proposition", "field": "unique_mechanism"},
    hasDataCheck: {"kind": "single", "table": "dna_value_proposition", "field": "unique_mechanism"},
    multiSelect: false,
    promptTemplate: `This is about the value proposition — specifically \${aspect_label}: \${value}.`,
    displayOrder: 4,
    status: `active`,
    notes: null,
  },
  {
    path: `value_proposition.elevator_pitch`,
    parentPath: `value_proposition`,
    stepLevel: 2,
    category: `value_proposition`,
    label: `Elevator pitch`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_value_proposition", "field": "elevator_pitch"},
    hasDataCheck: {"kind": "single", "table": "dna_value_proposition", "field": "elevator_pitch"},
    multiSelect: false,
    promptTemplate: `This is about the value proposition — specifically \${aspect_label}: \${value}.`,
    displayOrder: 5,
    status: `active`,
    notes: null,
  },
  {
    path: `value_proposition.differentiators`,
    parentPath: `value_proposition`,
    stepLevel: 2,
    category: `value_proposition`,
    label: `Differentiators`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "jsonb_array", "table": "dna_value_proposition", "field": "differentiators"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 6,
    status: `active`,
    notes: null,
  },
  {
    path: `value_proposition.differentiators.item`,
    parentPath: `value_proposition.differentiators`,
    stepLevel: 3,
    category: `value_proposition`,
    label: `Differentiators`,
    surfaceKind: `item`,
    dataQuery: {"kind": "jsonb_array", "table": "dna_value_proposition", "field": "differentiators"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about the value proposition — specifically \${aspect_label}: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `brand_meaning.vision`,
    parentPath: `brand_meaning`,
    stepLevel: 2,
    category: `brand_meaning`,
    label: `Vision`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_brand_meaning", "field": "vision"},
    hasDataCheck: {"kind": "single", "table": "dna_brand_meaning", "field": "vision"},
    multiSelect: false,
    promptTemplate: `This is about brand meaning — specifically \${aspect_label}: \${value}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `brand_meaning.mission`,
    parentPath: `brand_meaning`,
    stepLevel: 2,
    category: `brand_meaning`,
    label: `Mission`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_brand_meaning", "field": "mission"},
    hasDataCheck: {"kind": "single", "table": "dna_brand_meaning", "field": "mission"},
    multiSelect: false,
    promptTemplate: `This is about brand meaning — specifically \${aspect_label}: \${value}.`,
    displayOrder: 1,
    status: `active`,
    notes: null,
  },
  {
    path: `brand_meaning.purpose`,
    parentPath: `brand_meaning`,
    stepLevel: 2,
    category: `brand_meaning`,
    label: `Purpose`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "dna_brand_meaning", "field": "purpose"},
    hasDataCheck: {"kind": "single", "table": "dna_brand_meaning", "field": "purpose"},
    multiSelect: false,
    promptTemplate: `This is about brand meaning — specifically \${aspect_label}: \${value}.`,
    displayOrder: 2,
    status: `active`,
    notes: null,
  },
  {
    path: `brand_meaning.values`,
    parentPath: `brand_meaning`,
    stepLevel: 2,
    category: `brand_meaning`,
    label: `Values`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "jsonb_array", "table": "dna_brand_meaning", "field": "values"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 3,
    status: `active`,
    notes: null,
  },
  {
    path: `brand_meaning.values.item`,
    parentPath: `brand_meaning.values`,
    stepLevel: 3,
    category: `brand_meaning`,
    label: `Values`,
    surfaceKind: `item`,
    dataQuery: {"kind": "jsonb_array", "table": "dna_brand_meaning", "field": "values"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about brand meaning — specifically \${aspect_label}: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `brand_proof.testimonial`,
    parentPath: `brand_proof`,
    stepLevel: 2,
    category: `brand_proof`,
    label: `A testimonial`,
    surfaceKind: `sub_category`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "table", "table": "src_testimonials", "filter": "is_archived=false"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `brand_proof.testimonial.item`,
    parentPath: `brand_proof.testimonial`,
    stepLevel: 3,
    category: `brand_proof`,
    label: `A testimonial`,
    surfaceKind: `item`,
    dataQuery: {"kind": "table", "table": "src_testimonials", "filter": "is_archived=false"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about brand proof — specifically a testimonial from \${client_name}: "\${quote}".`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `brand_proof.statistic`,
    parentPath: `brand_proof`,
    stepLevel: 2,
    category: `brand_proof`,
    label: `A statistic`,
    surfaceKind: `sub_category`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "table", "table": "src_statistics", "filter": "is_archived=false"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 1,
    status: `active`,
    notes: null,
  },
  {
    path: `brand_proof.statistic.item`,
    parentPath: `brand_proof.statistic`,
    stepLevel: 3,
    category: `brand_proof`,
    label: `A statistic`,
    surfaceKind: `item`,
    dataQuery: {"kind": "table", "table": "src_statistics", "filter": "is_archived=false"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about brand proof — specifically the statistic: "\${stat}" (Source: \${source}).`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `brand_proof.story`,
    parentPath: `brand_proof`,
    stepLevel: 2,
    category: `brand_proof`,
    label: `A story / case study`,
    surfaceKind: `sub_category`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "table", "table": "src_stories", "filter": "is_archived=false"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 2,
    status: `active`,
    notes: null,
  },
  {
    path: `brand_proof.story.item`,
    parentPath: `brand_proof.story`,
    stepLevel: 3,
    category: `brand_proof`,
    label: `A story / case study`,
    surfaceKind: `item`,
    dataQuery: {"kind": "table", "table": "src_stories", "filter": "is_archived=false"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about brand proof — specifically the story "\${title}": \${narrative_or_summary}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `source_material.document`,
    parentPath: `source_material`,
    stepLevel: 2,
    category: `source_material`,
    label: `Which document?`,
    surfaceKind: `entity`,
    dataQuery: {"kind": "table", "table": "src_source_documents", "filter": "is_archived=false", "group_by": "type"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about source material — specifically the \${type} titled "\${title}": \${extracted_text_excerpt}.`,
    displayOrder: 0,
    status: `active`,
    notes: `entity acts as item leaf (multi-select). Type/tag/date are filter chips, not cascade steps.`,
  },
  {
    path: `own_research.entity`,
    parentPath: `own_research`,
    stepLevel: 2,
    category: `own_research`,
    label: `Which research item?`,
    surfaceKind: `entity`,
    dataQuery: {"kind": "table", "table": "src_own_research", "filter": "is_archived=false"},
    hasDataCheck: null,
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `own_research.entity.summary`,
    parentPath: `own_research.entity`,
    stepLevel: 3,
    category: `own_research`,
    label: `Summary`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "src_own_research", "field": "summary", "parent_param": "research_id"},
    hasDataCheck: {"kind": "single", "table": "src_own_research", "field": "summary", "parent_param": "research_id"},
    multiSelect: false,
    promptTemplate: `This is about own research — specifically \${aspect_label} from "\${title}": \${value}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `own_research.entity.methodology`,
    parentPath: `own_research.entity`,
    stepLevel: 3,
    category: `own_research`,
    label: `Methodology`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "src_own_research", "field": "methodology", "parent_param": "research_id"},
    hasDataCheck: {"kind": "single", "table": "src_own_research", "field": "methodology", "parent_param": "research_id"},
    multiSelect: false,
    promptTemplate: `This is about own research — specifically \${aspect_label} from "\${title}": \${value}.`,
    displayOrder: 1,
    status: `active`,
    notes: null,
  },
  {
    path: `own_research.entity.findings`,
    parentPath: `own_research.entity`,
    stepLevel: 3,
    category: `own_research`,
    label: `Key findings`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "jsonb_array", "table": "src_own_research", "field": "key_findings", "parent_param": "research_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 2,
    status: `active`,
    notes: null,
  },
  {
    path: `own_research.entity.findings.item`,
    parentPath: `own_research.entity.findings`,
    stepLevel: 4,
    category: `own_research`,
    label: `Key findings`,
    surfaceKind: `item`,
    dataQuery: {"kind": "jsonb_array", "table": "src_own_research", "field": "key_findings", "parent_param": "research_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about own research — specifically \${aspect_label} from "\${title}": \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `mission.entity`,
    parentPath: `mission`,
    stepLevel: 2,
    category: `mission`,
    label: `Which mission?`,
    surfaceKind: `entity`,
    dataQuery: {"kind": "table", "table": "missions"},
    hasDataCheck: null,
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `mission.entity.thesis`,
    parentPath: `mission.entity`,
    stepLevel: 3,
    category: `mission`,
    label: `Thesis`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "single", "table": "missions", "field": "thesis", "parent_param": "mission_id"},
    hasDataCheck: {"kind": "single", "table": "missions", "field": "thesis", "parent_param": "mission_id"},
    multiSelect: false,
    promptTemplate: `This is about a research mission — \${mission_name} — specifically \${aspect_label}: \${value}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `mission.entity.verticals`,
    parentPath: `mission.entity`,
    stepLevel: 3,
    category: `mission`,
    label: `Verticals`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "joined", "table": "mission_verticals", "parent_param": "mission_id", "parent_field": "mission_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 1,
    status: `active`,
    notes: null,
  },
  {
    path: `mission.entity.verticals.item`,
    parentPath: `mission.entity.verticals`,
    stepLevel: 4,
    category: `mission`,
    label: `Verticals`,
    surfaceKind: `item`,
    dataQuery: {"kind": "joined", "table": "mission_verticals", "parent_param": "mission_id", "parent_field": "mission_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about a research mission — \${mission_name} — specifically \${aspect_label}: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `mission.entity.stats`,
    parentPath: `mission.entity`,
    stepLevel: 3,
    category: `mission`,
    label: `Linked statistics`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "joined", "table": "mission_stats", "parent_param": "mission_id", "parent_field": "mission_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 2,
    status: `active`,
    notes: null,
  },
  {
    path: `mission.entity.stats.item`,
    parentPath: `mission.entity.stats`,
    stepLevel: 4,
    category: `mission`,
    label: `Linked statistics`,
    surfaceKind: `item`,
    dataQuery: {"kind": "joined", "table": "mission_stats", "parent_param": "mission_id", "parent_field": "mission_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about a research mission — \${mission_name} — specifically \${aspect_label}: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `mission.entity.inputs`,
    parentPath: `mission.entity`,
    stepLevel: 3,
    category: `mission`,
    label: `Linked source inputs`,
    surfaceKind: `aspect`,
    dataQuery: {"kind": "static"},
    hasDataCheck: {"kind": "joined", "table": "mission_inputs", "parent_param": "mission_id", "parent_field": "mission_id"},
    multiSelect: false,
    promptTemplate: null,
    displayOrder: 3,
    status: `active`,
    notes: null,
  },
  {
    path: `mission.entity.inputs.item`,
    parentPath: `mission.entity.inputs`,
    stepLevel: 4,
    category: `mission`,
    label: `Linked source inputs`,
    surfaceKind: `item`,
    dataQuery: {"kind": "joined", "table": "mission_inputs", "parent_param": "mission_id", "parent_field": "mission_id"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about a research mission — \${mission_name} — specifically \${aspect_label}: \${selected_items_joined}.`,
    displayOrder: 0,
    status: `active`,
    notes: null,
  },
  {
    path: `idea.entity`,
    parentPath: `idea`,
    stepLevel: 2,
    category: `idea`,
    label: `Which idea?`,
    surfaceKind: `entity`,
    dataQuery: {"kind": "table", "table": "ideas", "filter": "status='captured'"},
    hasDataCheck: null,
    multiSelect: true,
    promptTemplate: `This is about a captured idea: "\${idea_text}".`,
    displayOrder: 0,
    status: `active`,
    notes: `entity acts as item leaf (multi-select). Type filter is a UI chip, not a cascade step.`,
  },
]
